INSERT INTO ingredients (name, unit) VALUES ('Salt', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Pasta', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Mango', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Orange', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Basil', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Ketchup', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Yogurt', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Chocolate', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Bacon', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Lamb', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Vinegar', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Zucchini', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Banana', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Soy Sauce', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Turmeric', 'pieces');
INSERT INTO ingredients (name, unit) VALUES ('Coriander', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Honey', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Lemon Juice', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Milk', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Blueberry', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Mozzarella', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Pistachios', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Spinach', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Water', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Baking Powder', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Prawns', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Crab', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Yeast', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Broccoli', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Cumin', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Mustard Seeds', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Cabbage', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Garam Masala', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Paneer', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Stock', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Tomato', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Sugar', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Flour', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Mustard', 'pieces');
INSERT INTO ingredients (name, unit) VALUES ('Cream', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Pork', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Paprika', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Chicken', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Vanilla', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Baking Soda', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Chana', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Salmon', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Turkey', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Strawberry', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Tuna', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Beef', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Apple', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Oats', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Pepper', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Cashews', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Mayonnaise', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Eggplant', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Wheat', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Thyme', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Cheese', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Parsley', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Rice', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Quinoa', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Parmesan', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Vegetable Oil', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Dal', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Bell Pepper', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Chili Powder', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Walnuts', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Butter', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Garlic', 'ml');
INSERT INTO ingredients (name, unit) VALUES ('Onion', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Sesame Oil', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Carrot', 'grams');
INSERT INTO ingredients (name, unit) VALUES ('Oregano', 'ml');