-- Insert data into ingredients
-- Generated at: 2026-04-21T14:16:56.346257

INSERT INTO ingredients (name, unit) VALUES ('Flour', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Sugar', 'cups') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Salt', 'pieces') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Pepper', 'kg') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Olive Oil', 'kg') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Butter', 'oz') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Eggs', 'grams') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Chicken', 'grams') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Beef', 'cups') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Salmon', 'oz') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Tomato', 'kg') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Lettuce', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Cucumber', 'cups') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Onion', 'kg') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Garlic', 'oz') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Cheese', 'oz') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Milk', 'oz') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Pasta', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Rice', 'ml') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Bread', 'grams') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Potatoes', 'oz') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Carrots', 'ml') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Broccoli', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Spinach', 'oz') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Mushrooms', 'grams') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Bell Pepper', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Lemon', 'kg') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Lime', 'grams') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Ginger', 'grams') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Basil', 'kg') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Oregano', 'ml') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Thyme', 'grams') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Cinnamon', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Vanilla', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Chocolate', 'cups') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Honey', 'pieces') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Vinegar', 'kg') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Wine', 'grams') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Beer', 'pieces') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Coffee', 'ml') RETURNING id;
