-- Insert data into ingredients
-- Generated at: 2026-04-20T10:07:35.615265

INSERT INTO ingredients (name, unit) VALUES ('Flour', 'oz') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Sugar', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Salt', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Pepper', 'pieces') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Olive Oil', 'kg') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Butter', 'kg') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Eggs', 'cups') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Chicken', 'ml') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Beef', 'oz') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Salmon', 'cups') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Tomato', 'kg') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Lettuce', 'oz') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Cucumber', 'pieces') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Onion', 'grams') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Garlic', 'ml') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Cheese', 'oz') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Milk', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Pasta', 'grams') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Rice', 'ml') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Bread', 'oz') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Potatoes', 'grams') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Carrots', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Broccoli', 'oz') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Spinach', 'cups') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Mushrooms', 'kg') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Bell Pepper', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Lemon', 'cups') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Lime', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Ginger', 'cups') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Basil', 'liter') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Oregano', 'kg') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Thyme', 'pieces') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Cinnamon', 'cups') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Vanilla', 'kg') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Chocolate', 'cups') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Honey', 'grams') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Vinegar', 'grams') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Wine', 'cups') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Beer', 'cups') RETURNING id;
INSERT INTO ingredients (name, unit) VALUES ('Coffee', 'cups') RETURNING id;
