-- Insert data into menu_items
-- Generated at: 2026-04-21T14:16:56.348971

INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (73, 'Nachos', 'Environment machine bring drop see grow medical water head.', 15.8, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (74, 'Caesar Salad', 'Try manage occur where budget debate ten certain last character bank over occur.', 15.87, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (75, 'Pasta Carbonara', 'Above everybody few study television notice beautiful parent contain point.', 15.31, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (76, 'Ice Cream', 'Leave smile professor improve bit when politics report pass near political.', 17.8, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (77, 'Coca Cola', 'Accept bill probably shake marriage training process quite husband tax usually author.', 24.36, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (78, 'Vegetables', 'Story ago house phone job form mouth actually amount foot recent.', 18.79, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (73, 'Calamari', 'Ask that look get big lose station government.', 28.56, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (74, 'Caesar Salad', 'Value discuss involve media bar fly fund against them.', 21.18, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (75, 'Fish Tacos', 'Onto wife beyond tax whatever suffer character cause three.', 8.84, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (76, 'Ice Cream', 'Environment perhaps for if tree small player soldier per environment writer her rise.', 26.51, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (77, 'Wine', 'Word year first address lose traditional small simple blue middle environment stop.', 24.15, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (78, 'Vegetables', 'Unit list size white wait behind family.', 21.81, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (73, 'Nachos', 'Simply professor boy fight time sense need develop goal rather far anyone candidate.', 28.55, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (74, 'Caprese Salad', 'Herself return focus walk message college work entire light PM.', 12.56, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (75, 'Chicken Parmesan', 'Indeed remain network better once government.', 15.35, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (76, 'Crème Brûlée', 'Able however right may buy various leg send.', 9.8, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (77, 'Coffee', 'This site practice look early drug worker.', 23.49, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (78, 'Bread Basket', 'Type note economic star think owner ball nation shoulder organization provide their reduce.', 14.39, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (73, 'Nachos', 'Leader doctor into both fear next prevent.', 27.2, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (74, 'Caprese Salad', 'Suffer recent majority up feel executive church require design PM condition pick smile.', 23.78, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (75, 'Pasta Carbonara', 'Color institution government ahead worker father with reduce.', 10.93, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (76, 'Cheesecake', 'Soldier know generation career can rest town eat short east.', 17.96, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (77, 'Coffee', 'Station training movement like remember partner since possible bar.', 16.44, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (78, 'French Fries', 'Book manage wonder side red possible even officer PM inside.', 24.98, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (73, 'Spring Rolls', 'Door stay always mind other two event.', 10.44, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (74, 'Caprese Salad', 'Ground language possible blood high interesting difficult including mean water office eight worker.', 11.12, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (75, 'Pasta Carbonara', 'Live professor approach herself you discuss yard model edge piece price.', 28.26, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (76, 'Crème Brûlée', 'Something door about light agreement give foreign customer relate.', 11.48, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (77, 'Coca Cola', 'Huge single medical crime them pay want vote spring up I bed.', 14.61, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (78, 'French Fries', 'Very side vote later page produce policy large animal community image.', 25.39, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (73, 'Bruschetta', 'Book stop son low receive spend partner green protect.', 7.46, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (74, 'Minestrone', 'Card clearly sound now around society air according central last opportunity.', 11.89, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (75, 'Beef Steak', 'To data society media college charge officer head check artist letter so.', 7.56, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (76, 'Tiramisu', 'Up with management subject box pass line later.', 18.51, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (77, 'Lemonade', 'Herself dinner group perhaps strategy under bill start leave option better.', 26.48, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (78, 'French Fries', 'Commercial medical theory grow animal fall stay consider.', 6.16, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (73, 'Nachos', 'Hair apply girl space fast rate million officer star group.', 21.35, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (74, 'Greek Salad', 'Serve white class interesting cup them full help.', 13.66, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (75, 'Fish Tacos', 'Kid election put more ever thousand offer.', 10.1, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (76, 'Crème Brûlée', 'Month agree respond list do whom.', 8.9, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (77, 'Wine', 'Large night role research end somebody.', 15.2, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (78, 'Bread Basket', 'Feel record three sure either ball special million fast.', 17.8, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (73, 'Calamari', 'Top police inside movie officer your section economic benefit various best weight court.', 7.53, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (74, 'Greek Salad', 'Enter interest race tree future close maybe.', 21.39, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (75, 'Fish Tacos', 'Sense whose way beyond within news drug good hour resource toward upon entire song.', 22.43, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (76, 'Tiramisu', 'Hot give stuff lose result environment.', 22.3, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (77, 'Lemonade', 'Former today use too race mother break recognize his economic defense.', 10.01, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (78, 'Coleslaw', 'Of another get drive put million where push.', 14.11, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (73, 'Calamari', 'Structure five law have big bad last trial discover.', 23.76, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (74, 'Greek Salad', 'Send physical idea question prevent follow sing cell bill despite bar nothing country.', 14.78, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (75, 'Grilled Salmon', 'Recent ground expert yes up science reveal light way have.', 19.08, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (76, 'Tiramisu', 'Huge trade item against little instead marriage stay people buy language.', 9.66, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (77, 'Coffee', 'Give modern small four white city allow development court in.', 18.32, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (78, 'Rice Pilaf', 'Theory city law feel ten store.', 25.33, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (73, 'Nachos', 'Cover clearly quality offer goal scientist fire thing cover drop statement.', 14.35, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (74, 'Tomato Soup', 'Left stop main good yet positive above century science.', 22.5, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (75, 'Fish Tacos', 'There seek sure town better develop watch tell probably commercial long.', 15.76, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (76, 'Chocolate Cake', 'Run hit director my throw level get participant during.', 23.61, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (77, 'Coffee', 'Wear do performance benefit still according really toward the simply leader dog population.', 17.99, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (78, 'Bread Basket', 'Never give become nearly quickly address far source.', 14.11, true) RETURNING id;
