-- Insert data into menu_items
-- Generated at: 2026-04-20T10:07:35.618167

INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (55, 'Nachos', 'Skill tax through effect decade difference before character.', 13.15, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (56, 'Tomato Soup', 'Organization red between west station can step guy.', 26.96, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (57, 'Grilled Salmon', 'Direction in piece he gas wear process cultural believe plan this pattern this.', 27.7, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (58, 'Tiramisu', 'Paper others mean ok give get fact Democrat themselves me.', 19.86, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (59, 'Wine', 'Than debate close score little national guy western debate.', 15.14, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (60, 'Bread Basket', 'Wife cut weight example serve begin major thousand establish local.', 10.34, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (55, 'Nachos', 'Parent amount language he we country only day feeling page control experience argue.', 27.37, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (56, 'Greek Salad', 'Strategy idea act behavior discuss deal sense candidate able.', 18.7, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (57, 'Fish Tacos', 'Enough guy view tend right peace bring eye fact life nice indicate.', 9.85, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (58, 'Cheesecake', 'Play consider data medical order after.', 28.1, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (59, 'Coffee', 'Big measure major quite relate local heart evidence laugh fear remember including admit develop.', 20.99, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (60, 'Coleslaw', 'Teacher military draw at play student father sit face.', 18.24, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (55, 'Spring Rolls', 'Try author from dog try method agreement firm wrong enter.', 13.88, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (56, 'Caprese Salad', 'Speech collection every paper him sense long nor production strong.', 7.35, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (57, 'Pasta Carbonara', 'Shoulder story either ready color carry Democrat.', 9.79, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (58, 'Cheesecake', 'Per computer wife officer clear seven detail environmental cultural peace plant beyond.', 12.27, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (59, 'Coca Cola', 'Sister information position always whatever production ok success media man save clearly.', 27.02, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (60, 'Coleslaw', 'Local make time notice professor letter personal maintain suffer unit national memory.', 27.74, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (55, 'Bruschetta', 'Dog well amount it training eight edge author group might until.', 9.77, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (56, 'Tomato Soup', 'Home weight cold letter customer discuss room seem source ten drive if condition.', 14.34, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (57, 'Fish Tacos', 'Society oil despite behind new include official back he Democrat.', 24.07, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (58, 'Ice Cream', 'Hundred themselves financial reduce not say necessary course imagine.', 20.47, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (59, 'Wine', 'City drive sister available feeling should scientist operation.', 15.4, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (60, 'Coleslaw', 'Society poor fear successful tough listen occur why.', 13.2, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (55, 'Calamari', 'Certain or job walk every peace we customer age school.', 6.69, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (56, 'Tomato Soup', 'Page dream particular our produce race gun five fine less suddenly decision sing.', 17.48, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (57, 'Pasta Carbonara', 'Upon pattern lead source coach debate send Mrs though.', 8.63, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (58, 'Tiramisu', 'Both night heart allow skill federal administration best dark environment.', 13.59, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (59, 'Coffee', 'Large move generation particular reveal school.', 10.71, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (60, 'Vegetables', 'Reason late us question most group sister executive suffer small spring out similar.', 28.11, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (55, 'Bruschetta', 'With yourself thank factor usually head want whether parent development forward network.', 13.8, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (56, 'Tomato Soup', 'Analysis mouth operation onto coach sister.', 12.14, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (57, 'Fish Tacos', 'Majority civil thing action choose that out.', 8.17, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (58, 'Chocolate Cake', 'Director plant remain card bit media eye someone food radio.', 18.88, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (59, 'Coffee', 'Necessary join truth half gas true election expect daughter likely here author range.', 8.16, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (60, 'Bread Basket', 'Director require toward design begin late gas city how nature performance.', 22.16, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (55, 'Nachos', 'Against science nor something material dream family treatment economic talk parent talk.', 19.42, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (56, 'Caesar Salad', 'Beautiful explain do price growth customer teacher.', 12.31, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (57, 'Fish Tacos', 'Federal speech few color child very across offer agency exist sing nor.', 19.16, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (58, 'Crème Brûlée', 'Begin election quickly project someone grow look today.', 15.62, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (59, 'Iced Tea', 'Sign least card direction organization to ground recognize listen sell yes.', 28.4, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (60, 'French Fries', 'Lose baby offer best true spend election range bit seven low save sign.', 29.42, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (55, 'Bruschetta', 'Risk out among program whether training can unit over remain.', 19.64, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (56, 'Greek Salad', 'Within woman scene establish song along.', 24.86, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (57, 'Pasta Carbonara', 'Room dream support later international executive happy decide special significant officer degree evening concern.', 17.73, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (58, 'Tiramisu', 'Skin prove high their eat boy pressure to of natural.', 6.81, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (59, 'Coca Cola', 'Never citizen Congress open behind challenge themselves.', 9.19, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (60, 'Rice Pilaf', 'Kind various marriage usually process at.', 17.17, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (55, 'Mozzarella Sticks', 'Office structure Democrat while ready news.', 28.54, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (56, 'Caprese Salad', 'Other offer eight participant reach enter son lawyer recently down use share bad.', 14.66, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (57, 'Beef Steak', 'Same once laugh person interesting no cut house watch dream read.', 13.67, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (58, 'Chocolate Cake', 'Rise yeah require fight large such feel decide big career buy budget draw.', 29.53, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (59, 'Lemonade', 'Power will six region put likely direction without might west call soldier must.', 19.28, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (60, 'Vegetables', 'Woman attention physical society support carry two brother purpose painting rule hundred.', 18.49, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (55, 'Spring Rolls', 'General official wind why benefit than.', 29.23, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (56, 'Greek Salad', 'Almost particularly college go language position we happy these character financial leader.', 26.73, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (57, 'Pasta Carbonara', 'Write probably rich personal real gun care red surface less.', 24.8, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (58, 'Cheesecake', 'Stop college up ready detail involve rate work need song government herself.', 21.09, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (59, 'Coffee', 'Owner wish almost environment base third office both information product skin indeed.', 13.62, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (60, 'Vegetables', 'Day food country billion sister economic reach class stage somebody.', 10.02, true) RETURNING id;
