-- Insert data into menu_items
-- Generated at: 2026-04-19T14:26:33.582137

INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (49, 'Mozzarella Sticks', 'Community time detail bag contain leave.', 17.63, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (50, 'Caesar Salad', 'Decade floor mouth part detail blue step anything cold.', 14.34, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (51, 'Pasta Carbonara', 'Run serve mind nearly agency house tree father.', 20.77, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (52, 'Chocolate Cake', 'Data kitchen treatment move five like term little PM eye most million.', 12.49, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (53, 'Coffee', 'Usually international reach crime off western parent style management sure high modern relationship.', 29.46, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (54, 'Rice Pilaf', 'Country sit reality cold woman start fear official industry interesting.', 6.18, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (49, 'Calamari', 'Series much political tend enough country hair consider message great throughout Mrs food.', 15.66, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (50, 'Greek Salad', 'Us respond already scene memory eight lot series design reality.', 19.12, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (51, 'Beef Steak', 'Rather tax method indicate write full citizen set hospital report oil thing against pattern.', 13.53, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (52, 'Ice Cream', 'Kitchen home quality arrive about identify happen lose half message.', 20.81, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (53, 'Iced Tea', 'Policy subject class attorney fund feeling race data tell poor training truth suddenly.', 9.02, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (54, 'Rice Pilaf', 'Knowledge citizen she half sit that yourself both interesting focus may current theory.', 17.61, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (49, 'Spring Rolls', 'Make sort resource artist since exactly wife.', 25.24, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (50, 'Minestrone', 'Century form cup rather evening third.', 14.12, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (51, 'Pasta Carbonara', 'Blood less future argue choose admit.', 6.82, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (52, 'Tiramisu', 'Health benefit environmental ten article president.', 28.19, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (53, 'Iced Tea', 'Born own floor south work reduce charge pretty still opportunity.', 22.51, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (54, 'French Fries', 'Manage put bit new no head great develop total land physical.', 28.78, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (49, 'Spring Rolls', 'Know movement wall American identify attention sense.', 15.95, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (50, 'Tomato Soup', 'Front include remember step upon amount white finish dinner common prove.', 9.12, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (51, 'Beef Steak', 'Court political lead public hair have class street member continue push care.', 10.62, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (52, 'Ice Cream', 'Glass child recognize say wear TV specific low full defense race.', 28.79, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (53, 'Coca Cola', 'Room somebody provide Democrat for want inside another nice.', 27.45, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (54, 'Coleslaw', 'Attack material point music window television position discussion dog if situation.', 29.31, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (49, 'Mozzarella Sticks', 'Skin clearly best happen people media environmental real behavior break.', 8.32, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (50, 'Greek Salad', 'Continue start six morning system business such writer.', 27.65, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (51, 'Chicken Parmesan', 'Mother here moment skill particularly piece.', 22.28, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (52, 'Chocolate Cake', 'Get finally society after six drug stand can hold growth.', 10.16, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (53, 'Coffee', 'Read detail child ten different girl discussion send them sing there sing.', 18.59, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (54, 'Rice Pilaf', 'Eat girl its Democrat community apply table smile beyond focus everything not.', 18.85, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (49, 'Mozzarella Sticks', 'Word analysis situation arrive watch party really leg our senior discuss like.', 8.22, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (50, 'Greek Salad', 'After affect table child perform Mr bit hand less.', 26.64, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (51, 'Beef Steak', 'Create better dream pull what science article month image back draw.', 29.06, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (52, 'Cheesecake', 'Because artist college officer stuff perform address same recently real level.', 6.58, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (53, 'Wine', 'Support image street including school between music computer product begin.', 22.03, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (54, 'Bread Basket', 'Hold imagine want evidence across process either sort someone main all participant.', 19.74, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (49, 'Spring Rolls', 'Finish in space visit learn six law coach art full fish style organization.', 27.46, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (50, 'Minestrone', 'Generation type high prevent experience process rather that society beat.', 16.94, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (51, 'Chicken Parmesan', 'Bill difficult study husband year such poor step report.', 27.59, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (52, 'Tiramisu', 'Enough store inside how forward manage maybe out many great.', 14.63, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (53, 'Wine', 'Financial serious report will some why particularly customer read course field where how.', 14.7, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (54, 'Rice Pilaf', 'Able voice activity away cup growth actually.', 10.14, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (49, 'Spring Rolls', 'Lose these quite field feeling ask.', 25.42, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (50, 'Minestrone', 'Southern appear woman standard voice large mother product.', 21.29, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (51, 'Fish Tacos', 'Public stuff recently and mother so.', 24.26, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (52, 'Crème Brûlée', 'Happy consider nature another style glass bag beyond as.', 24.38, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (53, 'Wine', 'Red himself feel management break pull happy.', 28.4, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (54, 'Rice Pilaf', 'Those population consider high nice agree rise institution.', 16.55, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (49, 'Spring Rolls', 'Skill instead safe technology more pattern suffer who show early home record.', 16.52, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (50, 'Greek Salad', 'Experience letter yourself so heart garden player require short room power.', 7.03, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (51, 'Pasta Carbonara', 'That out industry market white thousand.', 26.84, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (52, 'Cheesecake', 'Approach let public nearly student cut organization respond Mr contain hold certainly.', 20.43, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (53, 'Lemonade', 'Member suggest remain pressure kid success hold raise positive.', 11.46, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (54, 'Vegetables', 'Information lot must role behind become organization clearly indeed.', 19.05, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (49, 'Spring Rolls', 'Black miss feeling least within for participant general standard fund long.', 27.14, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (50, 'Minestrone', 'Radio partner now answer son pick sister Republican to ten end table machine.', 19.87, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (51, 'Beef Steak', 'Describe kid morning charge relate top yourself hope reality reveal.', 14.99, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (52, 'Crème Brûlée', 'Arm television good ever his man detail us billion.', 7.3, false) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (53, 'Iced Tea', 'Able laugh card health generation president already.', 13.05, true) RETURNING id;
INSERT INTO menu_items (category_id, name, description, base_price, is_active) VALUES (54, 'French Fries', 'Director second seek care one page close special whether boy space responsibility build.', 23.61, false) RETURNING id;
